config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :toppages, only: [:index]
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :favorites
      get :reviews
    end
  end
  
  resources :items, only: [:index, :create] do
    collection do 
      get :fav_ranking
      get :rev_ranking
      get :search
    end
    resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  
  resources :favorites, only: [:create, :destroy]
end

app/models/item.rb
class Item < ApplicationRecord
    validates :name, presence: true
    validates :price, presence: true
    validates :content, presence: true
    validates :item_code, presence: true, uniqueness: true
    
    has_many :favorites
    has_many :liked_items, through: :favorites, source: :user
    has_many :reviews
    has_many :comented_items, through: :reviews, source: :user
    
    accepts_nested_attributes_for :reviews
    
    def self.create_fav_ranking
      Item.find(Favorite.group(:item_id).order('count(item_id) desc').limit(15).pluck(:item_id))
    end
    
    def self.create_rev_ranking
      Item.find(Review.group(:item_id).order('count(item_id) desc').limit(15).pluck(:item_id))
    end
    
    def average
      self.reviews.average(:rating)
    end  
    
    # rakuten_web_service内のclassで使えるようにアプリケーションIDを設定
    RakutenWebService.configure do |c|
      c.application_id = 1008590106441031375
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :require_user_logged_in
  
  def index
    # ARGV[0]で実行時の1つめのパラメータを取得、存在しない場合は'Ruby'を設定
    keyword = ARGV[0] || 'soccerball'
    
    # rakuten_web_serviceの使用法に乗っ取りHTTPリクエストを送ってデータを取得
    @Ritems = RakutenWebService::Ichiba::Item.search(keyword: keyword)
    
    @items = Item.order(id: :desc)
  end
  
  def search
    if params[:keyword]
      @Ritems = RakutenWebService::Ichiba::Item.search(keyword: params[:keyword])
    end
    
    @items = Item.order(id: :desc)
  end
  
  def create
    @item = Item.new(item_params)
    
    #未追加の商品をレビューする時
    if params[:num] == '1'
      if @item.save
        redirect_to item_reviews_path(@item)
      else
        flash.now[:danger] = '商品登録に失敗しました。'
        redirect_back(fallback_location: root_path)
      end
    #未追加の商品をお気に入りした時
    else
      if @item.save
        current_user.favorite(@item)
        flash[:success] = '商品をお気に入りしました'
        redirect_back(fallback_location: root_path)
      else
        flash.now[:danger] = 'お気に入り出来ませんでした'
        redirect_back(fallback_location: root_path)
      end
    end
  end

  def destroy
  end
  
  def fav_ranking
    @fav_items = Item.create_fav_ranking
  end
  
  def rev_ranking
    @rev_items = Item.create_rev_ranking
  end
  
  private

  def item_params
    params.permit(:image, :name, :price, :content, :item_code)
  end
end

app/views/items/_items.html.erb
<div class="table-responsive-sm">
  <table class="table table-hover table-bordered">
    <tbody>
      <% items.each do |item| %>
      <tr>
      　<td class=""><img src= "<%= item.image %>" ></td>
      　<td class=""><%= item.name %></td>
      　<td class=""><%= item.price %>円</td>
      　<td class=""><%= item.content %></td>
      　<% if item.average %>
        　<td class=""><%= link_to item.average, item_reviews_path(item) %></td>
        <% else %>
        　<td class=""><%= link_to 'レビュー', item_reviews_path(item) %></td>
        <% end %>
      　<td class=""><%= render 'favorites/favorite_button', item: item %></button></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate items %>
</div>

app/views/items/_search_items.html.erb
   <%= form_with(url: search_items_path, method: :get, local: true) do |f| %>
     <div class="d-flex justify-content-center">
      <div class="form-group">
       <%= f.text_field :keyword, placeholder: "キーワードから探す", class: 'form-control', style: 'width: 400px;' %>
      </div>
      <div class="form-group mt-1">
       <%= button_tag type: "submit" do %>
        <span class="fas fa-search" style="color: gray;"></span>
       <% end %>
      </div>
     </div>
   <% end %>
  
  <div class="table-responsive-sm">
   <table class="table table-hover table-bordered">
    <thead style="color: white; background-color: #bf0000;">
      <tr>
        <th>画像</th>
        <th>商品名</th>
        <th>価格</th>
        <th>概要</th>
        <th>評価</th>
        <th></th>
      </tr>
    </thead>
  
    <tbody>
      <% ritems.first(20).each do |ritem| %>
        <% item = items.find_by(item_code: ritem['itemCode']) %>
        <% if item %>
          <tr>
          　<td class=""><img src= "<%= item.image %>" ></td>
          　<td class=""><%= link_to item.name,  ritem['itemUrl']%></td>
          　<td class=""><%= item.price %>円</td>
          　<td class=""><%= item.content %></td>
          　<% if item.average %>
            　<td class=""><%= link_to item.average, item_reviews_path(item) %></td>
            <% else %>
            　<td class=""><%= link_to 'レビュー', item_reviews_path(item) %></td>
            <% end %>
          　<td class=""><%= render 'favorites/favorite_button', item: item %></button></td>
          </tr>
        <% else %>
          <tr>
          　<td class=""><img src= "<%= ritem['smallImageUrls'][0]%>" ></td>
          　<td class=""><%= link_to ritem['itemName'],  ritem['itemUrl']%></td>
          　<td class=""><%= ritem.price %>円</td>
          　<td class=""><%= ritem['itemCaption'] %></td>
          　<td class="">
          　  <%= form_with(url: items_path, local: true) do |f| %>
              <%= hidden_field_tag :num, 1 %>
              <%= hidden_field_tag :image, ritem['smallImageUrls'][0]%>
              <%= hidden_field_tag :name, ritem['itemName'] %>
              <%= hidden_field_tag :price, ritem.price %>
              <%= hidden_field_tag :content, ritem['itemCaption']%>
              <%= hidden_field_tag :item_code, ritem['itemCode']%>
              <%= f.submit 'レビュー', class: 'btn btn-primary btn-sm' %>
             <% end %>
          　</td>
          　<td class="">
          　   <%= form_with(url: items_path, local: true) do |f| %>
                <%= hidden_field_tag :num, 2 %>
                <%= hidden_field_tag :user_id, current_user.id %>
                <%= hidden_field_tag :image, ritem['smallImageUrls'][0]%>
                <%= hidden_field_tag :name, ritem['itemName'] %>
                <%= hidden_field_tag :price, ritem.price %>
                <%= hidden_field_tag :content, ritem['itemCaption']%>
                <%= hidden_field_tag :item_code, ritem['itemCode']%>
                <%= button_tag type: "submit", class: "border-0", style: "background-color: white;" do %>
                  <i class="far fa-star" onMouseOut="this.style.background=''" onMouseOver="this.style.background='gold'"></i>
                <% end %>
              <% end %>
             </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
   </table>
  </div>

app/views/items/fav_ranking.html.erb
<div class="center jumbotron p-1" style="background-color: #f8f8ff;">
  <div class="text-center">
    <h1 style="color: #bf0000;">お気に入り数ランキングTOP15</h1>
  </div>
</div>

<div class="table-responsive-sm">
  <table class="table table-hover table-bordered">
    <thead style="color: white; background-color: #bf0000;">
      <tr>
        <th>順位</th>
        <th>件数</th>
        <th>画像</th>
        <th>商品名</th>
        <th>価格</th>
        <th>商品概要</th>
        <th>評価</th>
        <th></th>
      </tr>
    </thead>
    
    <tbody>
      <% lastFavoriteCount = 0 %>
      <% j = 1 %>
      <% @fav_items.first(15).each.with_index(1) do |item, i| %>
      <tr>
        <% if i == 1 %>
          <% lastFavoriteCount = item.liked_items.count %>
        <% end %>
        <% if lastFavoriteCount != item.liked_items.count %>
          <td class=""><%= i %>位</td>
          <% lastFavoriteCount = item.liked_items.count %>
          <% j = i %>
        <% else %>
          <td class=""><%= j %>位</td>
          <% lastFavoriteCount = item.liked_items.count %>
        <% end %>
          <td class=""><%= item.liked_items.count %>件</td>
        　<td class=""><img src= "<%= item.image %>" %></td>
        　<td class=""><%= item.name %></td>
        　<td class=""><%= item.price %>円</td>
        　<td class=""><%= item.content %></td>
        　<% if item.average %>
        　   <td class=""><%= link_to item.average, item_reviews_path(item) %></td>
        　<% else %>
        　   <td class=""><%= link_to 'レビュー', item_reviews_path(item) %></td>
        　<% end %>
        　<td class=""><%= render 'favorites/favorite_button', item: item %></button></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/index.html.erb
<% if logged_in? %>
  <div class="center jumbotron pt-2 pb-2">
    <div class="text-center">
      <h1>Welcome to the RakutenItems Search Service</h1>
    </div>
  </div>

<%= render 'items/search_items', {ritems: @Ritems, items: @items} %>

<% else %>
  <div class="center jumbotron">
    <div class="text-center">
      <h1>Welcome to RakutenItems</h1>
      <%= link_to '新規会員登録はこちら', signup_path, class: 'btn btn-danger rounded-pill pr-4 pl-4' %>
    </div>
  </div>
<% end %>

app/views/items/ranking.html.erb
<div class="center jumbotron p-1" style="background-color: #f8f8ff;">
  <div class="text-center">
    <h1 style="color: #bf0000;">お気に入り数ランキングTOP15</h1>
  </div>
</div>

<div class="table-responsive-sm">
  <table class="table table-hover table-bordered">
    <tbody>
      <% @fav_items.each.with_index(1) do |item, i| %>
      <% count_liked_items = item.liked_items.count%>
      <tr>
        <td class=""><%= i %>位</td>
        <td class="">お気に入り数：<%= count_liked_items %>件</td>
      　<td class=""><img src= "<%= item.image %>" %></td>
      　<td class=""><%= item.name %></td>
      　<td class=""><%= item.price %>円</td>
      　<td class=""><%= item.content %></td>
      　<td class="">評価</td>
      　<td class=""><%= render 'favorites/favorite_button', item: item %></button></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/rev_ranking.html.erb
<div class="center jumbotron p-1" style="background-color: #f8f8ff;">
  <div class="text-center">
    <h1 style="color: #bf0000;">レビュー件数ランキングTOP15</h1>
  </div>
</div>

<div class="table-responsive-sm">
  <table class="table table-hover table-bordered">
    <thead style="color: white; background-color: #bf0000;">
      <tr>
        <th>順位</th>
        <th>件数</th>
        <th>画像</th>
        <th>商品名</th>
        <th>価格</th>
        <th>商品概要</th>
        <th>評価</th>
        <th></th>
      </tr>
    </thead>
    
    <tbody>
      <% lastReviewCount = 0 %>
      <% j = 1 %>
      <% @rev_items.first(15).each.with_index(1) do |item, i| %>
      <tr>
        <% if i == 1 %>
          <% lastReviewCount = item.comented_items.count %>
        <% end %>
        <% if lastReviewCount != item.comented_items.count %>
          <td class=""><%= i %>位</td>
          <% lastReviewCount = item.comented_items.count %>
          <% j = i %>
        <% else %>
          <td class=""><%= j %>位</td>
          <% lastReviewCount = item.comented_items.count %>
        <% end %>
          <td class=""><%= item.comented_items.count %>件</td>
        　<td class=""><img src= "<%= item.image %>" %></td>
        　<td class=""><%= item.name %></td>
        　<td class=""><%= item.price %>円</td>
        　<td class=""><%= item.content %></td>
        　<% if item.average %>
        　   <td class=""><%= link_to item.average, item_reviews_path(item) %></td>
        　<% else %>
        　<td class=""><%= link_to 'レビュー', item_reviews_path(item) %></td>
        　   <% end %>
        　<td class=""><%= render 'favorites/favorite_button', item: item %></button></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/items/search.html.erb
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong><%= params[:keyword] %></strong> の検索結果を表示しました
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
       <span aria-hidden="true">&times;</span>
    </button>
  </div>
  
<%= render 'items/search_items', {ritems: @Ritems, items: @items} %>