config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :toppages, only: [:index]
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :favorites
      get :reviews
    end
  end
  
  resources :items, only: [:index, :create] do
    collection do 
      get :fav_ranking
      get :rev_ranking
      get :search
    end
    resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  
  resources :favorites, only: [:create, :destroy]
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @item = Item.find(params[:item_id])
    @reviews = @item.reviews
    @users = User.order(id: :desc)
  end
  
  def new
    @review = Review.new
    @item = Item.find(params[:item_id])
  end

  def create
    @item = Item.find(params[:item_id])
    @review = @item.reviews.build(review_params)
    @review.user_id = current_user.id
    if @review.save
      flash[:success] ='レビューを投稿しました'
      redirect_to item_reviews_path(@item)
    else
      flash.now[:danger] = 'レビューを投稿できませんでした'
      render :new
    end
  end

  def edit
    @item = Item.find(params[:item_id])
    @review = @item.reviews.find(params[:id])
  end

  def update
    @item = Item.find(params[:item_id])
    @review = @item.reviews.find(params[:id])
    if (@review.user_id == current_user.id)
      if @review.update(review_params)
        flash[:success] ='レビューを編集しました'
        redirect_to item_reviews_path(@item)
      else
        flash.now[:danger] = 'レビューを編集できませんでした'
        render :edit
      end
    end
  end

  def destroy
    @item = Item.find(params[:item_id])
    @review = @item.reviews.find(params[:id])
    @review.destroy
    flash[:success] ='レビューを削除しました'
    redirect_back(fallback_location: root_path)
  end
  
  private
  
  def review_params
    params.require(:review).permit(:rating, :content)
  end
  
  def correct_user
    @Item = Item.find(params[:item_id])
    @review = @Item.reviews.find_by(id: params[:id])
    if @review == nil || @review.user_id != current_user.id 
      redirect_to root_path
    end
  end
end

app/views/reviews/edit.html.erb
<h5 class="mb-4"><%= @item.name %></h5>
<div class="media">
  <img class="align-self-start mr-3 img-fluid" src="<%= @item.image %>" alt="">
  <div class="media-body">
    <div class="mb-2">平均評価：<%= @item.average %></div>
    <div class="font-weight-bolder"><%= @item.price %>円</div>
  </div>
</div>
<div class="card mt-4 mb-4">
  <div class="card-body">
    <%= @item.content %>
  </div>
</div>

<div class="mt-4">
 <%= form_with(model: [@item, @review], local: true) do |f| %>
   <%= hidden_field_tag :user_id, current_user.id %>
    <div class="form-group">
      <%= f.label :rating, '評価：' %>
      <%= f.select :rating, [5,4,3,2,1], class: 'form-control' %>
    </div>
    
    <div class="form-group mb-4">
      <%= f.label :content, 'レビュー' %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>

    <div class="text-left mt-4">
    <%= f.submit '編集', class: 'btn btn-primary pl-4 pr-4' %>
    </div>
 <% end %>
</div>

app/views/reviews/index.html.erb
<h5 class="mb-4"><%= @item.name %></h5>
<div class="media mb-4">
  <img class="align-self-start mr-3 img-fluid" src="<%= @item.image %>" alt="">
  <div class="media-body">
    <div class="mb-2">平均評価：<%= @item.average %>
      <% unless current_user.reviewd?(@item) %>
        <span><%= link_to 'レビューを作成する', new_item_review_path(@item) %></span>
      <% end %>
    </div>
    <div class="font-weight-bolder"><%= @item.price %>円</div>
  </div>
</div>

<h2 class="text-center">商品レビュー一覧</h2>

<ul class="list-unstyled">
    <% @reviews.each do |review| %>
      <div class="ml-2 mt-2">
        <p class="mb-0"><%= link_to review.user.name, user_path(review.user) %></p>
      </div>
      <li class="media mb-4">
        <% if review.user.image? %>
          <img class="mr-4 rounded" style="height: 50px;" src="<%= review.user.image %>" alt="">
        <% else %>
          <img class="mr-4 rounded" src="<%= gravatar_url(review.user, { size: 50 }) %>" alt="">
        <% end %>
          <div class="media-body row">
            <div class="col-sm-10">
              <div><%= review.rating %></div>
              <div class="card"><%= review.content %></div>
            </div>
            <div class="col-sm-2">
              <% if current_user.id == review.user_id %>
                <%= link_to '編集', edit_item_review_path(@item, review) ,class: 'btn btn-success' %>
                <%= link_to "削除", item_review_path(item_id: @item, id: review), method: :delete, data: { confirm: "本当に削除しますか？" }, class: 'btn btn-danger' %>
              <% end %>
            </div>
          </div>
      </li>
    <% end %>
</ul>

app/views/reviews/new.html.erb
<h5 class="mb-4"><%= @item.name %></h5>
<div class="media">
  <img class="align-self-start mr-3 img-fluid" src="<%= @item.image %>" alt="">
  <div class="media-body">
    <div class="mb-2">平均評価：<%= @item.average %></div>
    <div class="font-weight-bolder"><%= @item.price %>円</div>
  </div>
</div>
<div class="card mt-4 mb-4">
  <div class="card-body">
    <%= @item.content %>
  </div>
</div>

<div class="mt-4">
 <%= form_with(model: [@item, @review], local: true) do |f| %>
   <%= hidden_field_tag :user_id, current_user.id %>
    <div class="form-group">
      <%= f.label :rating, '評価：' %>
      <%= f.select :rating, [5,4,3,2,1], class: 'form-control' %>
    </div>
    
    <div class="form-group mb-4">
      <%= f.label :content, 'レビュー' %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>

    <div class="text-left mt-4">
    <%= f.submit '作成', class: 'btn btn-primary pl-4 pr-4' %>
    </div>
 <% end %>
</div>