config/routes.rb
Rails.application.routes.draw do
  root to: 'items#index'
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  get 'signup', to: 'users#new'
  
  resources :toppages, only: [:index]
  
  resources :users, only: [:index, :show, :new, :create, :edit, :update] do
    member do
      get :favorites
      get :reviews
    end
  end
  
  resources :items, only: [:index, :create] do
    collection do 
      get :fav_ranking
      get :rev_ranking
      get :search
    end
    resources :reviews, only: [:index, :new, :create, :edit, :update, :destroy]
  end
  
  resources :favorites, only: [:create, :destroy]
end

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark" style="background-color: #bf0000;">
    <a class="navbar-brand mr-0" href="/">Items</a>
    <ul class="navbar-nav">
        <li class="nav-item dropdown">
        　<a href="#" class="navbar-brand dropdown-toggle" data-toggle="dropdown">Ranking</a>
            <div class="dropdown-menu pt-0">
            　<a class="dropdown-item" <%= link_to 'お気に入り数ランキング', fav_ranking_items_path %></a>
            　<a class="dropdown-item" <%= link_to 'レビュー件数ランキング', rev_ranking_items_path %></a>
            </div>
        </li>
    </ul>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav">
        <% if logged_in? %>
          <li class="nav-item"><%= link_to 'Users', users_path, class: 'nav-link' %></li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"><%= current_user.name %></a>
            <ul class="dropdown-menu dropdown-menu-right">
              <li class="dropdown-item"><%= link_to 'Profile', user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to 'お気に入り', favorites_user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to 'レビューした商品', reviews_user_path(current_user) %></li>
              <li class="dropdown-item"><%= link_to '会員情報変更', edit_user_path(current_user) %></li>
              <li class="dropdown-divider"></li>
              <li class="dropdown-item"><%= link_to 'ログアウトする', logout_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to 'ユーザー登録', signup_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>RakutenItems</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.2/js/all.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
      <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>